# Add funding links here if this project accepts sponsorships.
# Supported keys include:
# github: [username]
# patreon: username
# open_collective: project
# ko_fi: username
# tidelift: platform-name/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ["https://example.com"]
